"""Platform-aware thumbnail generation.

Public API used by media_native_host:

    init(backend=None)            detect OS/desktop and start the right backend;
                                  pass backend='pillow' (or any module name) to
                                  override auto-detection (e.g. if XDG is broken)
    is_available() -> bool        True if a real (non-null) backend was started
    supports_preemptive_queueing  bool flag; True if active backend supports prefetch
    request(file_path) -> bool    generate thumbnail; True when ready
    queue_preemptive(uris, mimes) background prefetch (no-op on some backends)
    thumb_path(file_path)         thumbnail cache path (pathlib.Path)
    is_valid(thumb_path, fp)      True if thumbnail is up-to-date for fp
    is_failed(fp)                 True if any fail-cache entry exists for fp
    file_uri(fp)                  GLib-compatible file:// URI for fp
    MIME_TYPES                    dict mapping file extension to MIME type string

Backend selection order (auto-detection):
  1. OS-specific module keyed on sys.platform:
       linux   → linux.py  → XDG desktop detection (Tumbler on XFCE, …)
       darwin  → darwin.py → qlmanage (Quick Look)
       win32   → win32.py  → IShellItemImageFactory via COM + GDI
  2. Pillow fallback, if no native backend found or available
  3. NullBackend – always succeeds so the daemon never needs to check for None
"""

import importlib
import re
import sys

from .xdg import XDGBackend, _cache_home, file_uri, MIME_TYPES


# ── NullBackend ─────────────────────────────────────────────────────────────────

class _NullBackend(XDGBackend):
    """Returned when no real backend can be initialised.

    All cache-path helpers are inherited from XDGBackend (so the daemon can
    still inspect the XDG cache for thumbnails generated by other tools).
    request() always returns False.
    """
    available                    = False
    supports_preemptive_queueing = False

    def request(self, file_path, timeout=30.0):
        return False


# ── Module state ────────────────────────────────────────────────────────────────

_backend: XDGBackend             = _NullBackend()
supports_preemptive_queueing     = False   # updated by init()


# ── Initialisation ──────────────────────────────────────────────────────────────

def _sanitize_name(name):
    """Strip non-alphanumeric chars and lowercase; safe as a Python module name."""
    return re.sub(r'[^a-z0-9]', '', name.lower())


def get_backend(explicit=None):
    """Return the best available backend instance; never returns None."""
    if explicit is not None:
        sanitized = _sanitize_name(explicit)
        try:
            mod = importlib.import_module(f'.{sanitized}', package=__name__)
            b   = mod.get_backend()
            if b is not None:
                return b
        except Exception:
            pass
        return _NullBackend()

    platform = _sanitize_name(sys.platform)
    try:
        mod = importlib.import_module(f'.{platform}', package=__name__)
        b   = mod.get_backend()
        if b is not None:
            return b
    except Exception:
        pass

    # No native backend found – try Pillow as a last resort before giving up.
    try:
        from . import pillow
        b = pillow.get_backend()
        if b is not None:
            return b
    except Exception:
        pass

    return _NullBackend()


def init(backend=None):
    """Detect the running environment and initialise the matching backend.

    backend – optional name of a specific backend module (e.g. 'pillow').
              Useful when native thumbnailing is available but misconfigured.
    """
    global _backend, supports_preemptive_queueing
    _backend                     = get_backend(explicit=backend)
    supports_preemptive_queueing = _backend.supports_preemptive_queueing


# ── Public API ──────────────────────────────────────────────────────────────────

def is_available():
    """True if a real (non-null) backend was successfully initialised."""
    return _backend.available


def request(file_path):
    """Generate a thumbnail for file_path.  Returns True when ready."""
    return _backend.request(file_path)


def queue_preemptive(uris, mimes):
    """Fire-and-forget background prefetch.

    uris  – list of file:// URIs
    mimes – parallel list of MIME type strings

    May be a no-op depending on the active backend.
    """
    _backend.queue_preemptive(uris, mimes)


def thumb_path(file_path):
    """Thumbnail cache path (pathlib.Path) for file_path."""
    return _backend.thumb_path(file_path)


def is_valid(thumb_path, file_path):
    """True if the cached thumbnail at thumb_path is up-to-date for file_path."""
    return _backend.is_valid(thumb_path, file_path)


def is_failed(file_path):
    """True if any fail-cache entry exists for file_path."""
    return _backend.is_failed(file_path)
